//# React Icons
export { MdLocationPin as Location } from "react-icons/md"
export { MdShoppingCart as ShoppingCart } from "react-icons/md"
export { IoIosCheckmarkCircleOutline as Confirm } from "react-icons/io"
export { IoAlertCircleOutline as Alert } from "react-icons/io5"
export { LuAsterisk as Required } from "react-icons/lu"
export { MdOutlineArrowBack as Back } from "react-icons/md"
export { IoFastFoodOutline as Logo } from "react-icons/io5"
export { FaClock as Clock } from "react-icons/fa"
export { IoSearchOutline as Find } from "react-icons/io5"
export { IoIosArrowUp as Arrow } from "react-icons/io"
export { IoIosCloseCircleOutline as Close } from "react-icons/io"
export { GoPencil as Pencil } from "react-icons/go"
export { PiMotorcycleFill as Motorcycle } from "react-icons/pi"
export { PiGarage as Local } from "react-icons/pi"
export { MdOutlineAttachMoney as Money } from "react-icons/md"
export { FaCreditCard as Card } from "react-icons/fa"
export { FaPix as Pix } from "react-icons/fa6"
